import { useEffect, useState } from "react"
import useUserContext from "../../Hooks/useUserContext"
import Modal from "../Modal/Modal"
import editProfileStyling from "./EditUserProfileStyling"


function EditUserProfile({ setEditModalOpen }) {

   const editStyles = editProfileStyling()
   const { loggedUser, dispatch } = useUserContext()

   const [tempLoggedUserData, setTempLoggedUserData] = useState({
      ...loggedUser.userInfo
   })

useEffect(()=> {
console.log('consoling: tempLoggedUserData :::', tempLoggedUserData )
},[tempLoggedUserData])

   const handleEditUserSubmit = () => {

   }

   // id: string(autogenerated)
   // title: string("mr", "ms", "mrs", "miss", "dr", "")
   // firstName: string(length: 2-50)
   // lastName: string(length: 2-50)
   // gender: string("male", "female", "other", "")
   // email: string(email)
   // dateOfBirth: string(ISO Date - value: 1/1/1900 - now)
   // registerDate: string(autogenerated)
   // phone: string(phone number - any format)
   // picture: string(url)
   // location: object(Location)

   // dateOfBirth: "1945-11-17T06:31:57.367Z"
   // email: "roberto.vega@example.com"
   // firstName: "Roberto"
   // gender: "male"
   // id: "60d0fe4f5311236168a109cd"
   // lastName: "Vega"
   // location: { street: '7675, Calle Mota', city: 'LogroÃ±o', state: 'Islas Baleares', country: 'Spain', timezone: '+6:00' }
   // phone: "949-368-211"
   // picture: "https://randomuser.me/api/portraits/med/men/25.jpg"
   // registerDate: "2021-06-21T21:02:07.872Z"
   // title: "mr"
   // updatedDate: "2021-06-21T2

   return (
      <Modal isOpen>
         <form onSubmit={handleEditUserSubmit} className={editStyles.modalContainer}>
            <div className={editStyles.inputWrapper}>
               <label htmlFor='firstName'>Change Name</label>
               <input type='text' id='firstName' value={tempLoggedUserData.firstName}
                  onChange={(e) => setTempLoggedUserData({ ...tempLoggedUserData, firstName: e.target.value })} 
                  className={editStyles.inputs}/>
            </div>

            <div className={editStyles.inputWrapper}>
               <label htmlFor='lastName'>Change Last Name</label>
               <input type='text' id='lastName' value={tempLoggedUserData.lastName}
                  onChange={(e) => setTempLoggedUserData({ ...tempLoggedUserData, lastName: e.target.value })} 
                  className={editStyles.inputs}/>
            </div>

            <div className={editStyles.inputWrapper}>
               <label htmlFor='DoB'>Change Date of Birth</label>
               <input type='date' id='DoB' value={tempLoggedUserData.dateOfBirth}
                  onChange={(e) => setTempLoggedUserData({ ...tempLoggedUserData, dateOfBirth: e.target.value })}
                  className={editStyles.inputs}/>
            </div>

            <div className={editStyles.inputWrapper}>
               <label htmlFor='phone'>Change Name</label>
               <input type='text' id='phone' value={tempLoggedUserData.phone} 
               onChange={(e) => setTempLoggedUserData({ ...tempLoggedUserData, phone: e.target.value })}
               className={editStyles.inputs}/>
            </div>

            {/* <div>
               <label htmlFor='pic'>Change Name</label>
               <input type='file' id='pic' value={loggedUser.userInfo.picture.toString()}/>
            </div> */}

            <div className={editStyles.buttonsContainer}>
               <button className={editStyles.submitButton} onClick={() => setEditModalOpen(false)}>Cancel</button>
               <button type="submit" className={editStyles.submitButton}>Submit Changes</button>
            </div>


         </form>
      </Modal>
   )
}

export default EditUserProfile